# Generated by Django 5.0 on 2024-01-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_attachment1_post_attachment2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment1',
            field=models.FileField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='attachment2',
            field=models.FileField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
